import { withAlpha } from "../color.ts";
import type { Palette } from "../palettes.ts";
import type { WorkbenchColors } from "./index.ts";

export function chrome(p: Palette): WorkbenchColors {
  return {
    // Window
    "window.activeBorder": p.border,
    "window.inactiveBorder": p.border,

    // Title bar
    "titleBar.activeBackground": p.bg,
    "titleBar.activeForeground": p.textSecondary,
    "titleBar.inactiveBackground": p.bg,
    "titleBar.inactiveForeground": p.muted,
    "titleBar.border": p.border,

    // Command center and menu bar
    "commandCenter.background": p.surface,
    "commandCenter.foreground": p.textSecondary,
    "commandCenter.border": p.border,
    "commandCenter.activeBackground": p.elevated,
    "commandCenter.activeForeground": p.text,
    "commandCenter.activeBorder": p.accentLine,
    "commandCenter.inactiveForeground": p.muted,
    "commandCenter.inactiveBorder": p.border,
    "commandCenter.debuggingBackground": p.warningSoft,
    "menubar.selectionBackground": p.elevated,
    "menubar.selectionForeground": p.text,

    // Activity bar
    "activityBar.background": p.bg,
    "activityBar.foreground": p.accent,
    "activityBar.inactiveForeground": p.muted,
    "activityBar.border": p.border,
    "activityBar.activeBorder": p.accent,
    "activityBar.activeFocusBorder": p.accent,
    "activityBar.dropBorder": p.accent,
    "activityBarTop.background": p.bg,
    "activityBarTop.foreground": p.accent,
    "activityBarTop.inactiveForeground": p.muted,
    "activityBarTop.activeBorder": p.accent,
    "activityBarTop.dropBorder": p.accent,
    "activityBarBadge.background": p.accent,
    "activityBarBadge.foreground": p.inverse,

    // Side bar
    "sideBar.background": p.bg,
    "sideBar.foreground": p.textSecondary,
    "sideBar.border": p.border,
    "sideBar.dropBackground": withAlpha(p.accent, 0.1),
    "sideBarTitle.background": p.bg,
    "sideBarTitle.foreground": p.text,
    "sideBarSectionHeader.background": p.bg,
    "sideBarSectionHeader.foreground": p.text,
    "sideBarSectionHeader.border": p.border,
    "sideBarActivityBarTop.border": p.border,
    "sideBarStickyScroll.background": p.bg,
    "sideBarStickyScroll.shadow": p.shadow,

    // Editor groups
    "editorGroup.border": p.border,
    "editorGroup.dropBackground": withAlpha(p.accent, 0.1),
    "editorGroup.emptyBackground": p.bg,
    "editorGroup.dropIntoPromptBackground": p.elevated,
    "editorGroup.dropIntoPromptForeground": p.text,
    "editorGroup.dropIntoPromptBorder": p.border,
    "editorGroupHeader.noTabsBackground": p.bg,
    "editorGroupHeader.tabsBackground": p.surface,
    "editorGroupHeader.tabsBorder": p.border,
    "editorPane.background": p.bg,
    "sideBySideEditor.horizontalBorder": p.border,
    "sideBySideEditor.verticalBorder": p.border,

    // Tabs
    "tab.border": p.border,
    "tab.activeBackground": p.bg,
    "tab.activeForeground": p.bright,
    "tab.activeBorder": p.bg,
    "tab.activeBorderTop": p.accent,
    "tab.unfocusedActiveBackground": p.bg,
    "tab.unfocusedActiveForeground": p.textSecondary,
    "tab.unfocusedActiveBorder": p.bg,
    "tab.unfocusedActiveBorderTop": withAlpha(p.accent, 0.5),
    "tab.inactiveBackground": p.surface,
    "tab.inactiveForeground": p.muted,
    "tab.unfocusedInactiveBackground": p.surface,
    "tab.unfocusedInactiveForeground": p.muted,
    "tab.hoverBackground": p.elevated,
    "tab.hoverForeground": p.text,
    "tab.unfocusedHoverBackground": p.elevated,
    "tab.unfocusedHoverForeground": p.text,
    "tab.selectedBackground": p.elevated,
    "tab.selectedForeground": p.text,
    "tab.selectedBorderTop": p.accentLine,
    "tab.activeModifiedBorder": p.warning,
    "tab.inactiveModifiedBorder": withAlpha(p.warning, 0.5),
    "tab.unfocusedActiveModifiedBorder": withAlpha(p.warning, 0.5),
    "tab.unfocusedInactiveModifiedBorder": withAlpha(p.warning, 0.5),
    "tab.lastPinnedBorder": p.borderStrong,
    "tab.dragAndDropBorder": p.accent,

    // Breadcrumbs
    "breadcrumb.background": p.bg,
    "breadcrumb.foreground": p.muted,
    "breadcrumb.focusForeground": p.text,
    "breadcrumb.activeSelectionForeground": p.accent,
    "breadcrumbPicker.background": p.elevated,

    // Panel
    "panel.background": p.bg,
    "panel.border": p.border,
    "panel.dropBorder": p.accent,
    "panelTitle.activeBorder": p.accent,
    "panelTitle.activeForeground": p.bright,
    "panelTitle.inactiveForeground": p.muted,
    "panelTitleBadge.background": p.accent,
    "panelTitleBadge.foreground": p.inverse,
    "panelInput.border": p.border,
    "panelSection.border": p.border,
    "panelSection.dropBackground": withAlpha(p.accent, 0.1),
    "panelSectionHeader.background": p.bg,
    "panelSectionHeader.foreground": p.text,
    "panelSectionHeader.border": p.border,
    "panelStickyScroll.background": p.bg,
    "panelStickyScroll.shadow": p.shadow,
    "outputView.background": p.bg,
    "outputViewStickyScroll.background": p.bg,

    // Status bar
    "statusBar.background": p.bg,
    "statusBar.foreground": p.textSecondary,
    "statusBar.border": p.border,
    "statusBar.focusBorder": p.accentLine,
    "statusBar.noFolderBackground": p.bg,
    "statusBar.noFolderForeground": p.textSecondary,
    "statusBar.noFolderBorder": p.border,
    "statusBar.debuggingBackground": p.warning,
    "statusBar.debuggingForeground": p.inverse,
    "statusBar.debuggingBorder": p.warning,
    "statusBarItem.focusBorder": p.accentLine,
    "statusBarItem.hoverBackground": p.elevated,
    "statusBarItem.hoverForeground": p.text,
    "statusBarItem.activeBackground": p.elevatedHover,
    "statusBarItem.compactHoverBackground": p.elevatedHover,
    "statusBarItem.prominentBackground": p.elevated,
    "statusBarItem.prominentForeground": p.text,
    "statusBarItem.prominentHoverBackground": p.elevatedHover,
    "statusBarItem.prominentHoverForeground": p.text,
    "statusBarItem.remoteBackground": p.accent,
    "statusBarItem.remoteForeground": p.inverse,
    "statusBarItem.remoteHoverBackground": withAlpha(p.accent, 0.85),
    "statusBarItem.remoteHoverForeground": p.inverse,
    "statusBarItem.offlineBackground": p.danger,
    "statusBarItem.offlineForeground": p.inverse,
    "statusBarItem.offlineHoverBackground": withAlpha(p.danger, 0.85),
    "statusBarItem.offlineHoverForeground": p.inverse,

    // Welcome page and extras
    "welcomePage.background": p.bg,
    "welcomePage.tileBackground": p.elevated,
    "welcomePage.tileHoverBackground": p.elevatedHover,
    "welcomePage.tileBorder": p.border,
    "welcomePage.progress.background": p.border,
    "welcomePage.progress.foreground": p.accent,
    "walkThrough.embeddedEditorBackground": p.surface,
    "walkthrough.stepTitle.foreground": p.bright,
    "banner.background": p.elevated,
    "banner.foreground": p.text,
    "banner.iconForeground": p.accent,
  };
}
