import type { Hex } from "../color.ts";
import type { Palette } from "../palettes.ts";

export interface TokenColor {
  name: string;
  scope: string[];
  settings: {
    foreground?: Hex;
    fontStyle?: string;
  };
}

/**
 * Scopes grouped by their final foreground in VS Code's Dark+ theme
 * (`dark_vs.json` followed by `dark_plus.json`). Every scope is listed once.
 */
export function tokenColors({ syntax }: Palette): TokenColor[] {
  return [
    {
      name: "Plain code, operators, embedded expressions and labels",
      scope: [
        "meta.embedded",
        "source.groovy.embedded",
        "string meta.image.inline.markdown",
        "variable.legacy.builtin.python",
        "meta.template.expression",
        "keyword.operator",
        "storage.modifier.import.java",
        "variable.language.wildcard.java",
        "storage.modifier.package.java",
        "entity.name.label",
      ],
      settings: { foreground: syntax.text },
    },
    {
      name: "Comments and Markdown quote markers",
      scope: ["comment", "punctuation.definition.quote.begin.markdown"],
      settings: { foreground: syntax.comment },
    },
    {
      name: "Declaration keywords, language constants, tags and preprocessor",
      scope: [
        "header",
        "constant.language",
        "entity.name.tag",
        "markup.changed",
        "meta.preprocessor",
        "entity.name.function.preprocessor",
        "meta.diff.header",
        "storage",
        "storage.type",
        "storage.modifier",
        "keyword.operator.noexcept",
        "punctuation.definition.template-expression.begin",
        "punctuation.definition.template-expression.end",
        "punctuation.section.embedded",
        "keyword",
        "keyword.operator.new",
        "keyword.operator.expression",
        "keyword.operator.cast",
        "keyword.operator.sizeof",
        "keyword.operator.alignof",
        "keyword.operator.typeid",
        "keyword.operator.alignas",
        "keyword.operator.instanceof",
        "keyword.operator.logical.python",
        "keyword.operator.wordlike",
        "punctuation.section.embedded.begin.php",
        "punctuation.section.embedded.end.php",
        "variable.language",
        "constant.character",
        "constant.other.option",
        "punctuation.definition.list.begin.markdown",
      ],
      settings: { foreground: syntax.storage },
    },
    {
      name: "Control flow, module keywords and special operators",
      scope: [
        "keyword.control",
        "source.cpp keyword.operator.new",
        "keyword.operator.delete",
        "keyword.other.using",
        "keyword.other.directive.using",
        "keyword.other.operator",
        "entity.name.operator",
      ],
      settings: { foreground: syntax.control },
    },
    {
      name: "Functions, methods and regular expression anchors",
      scope: [
        "entity.name.function",
        "support.function",
        "support.constant.handlebars",
        "source.powershell variable.other.member",
        "entity.name.operator.custom-literal",
        "keyword.operator.or.regexp",
        "keyword.control.anchor.regexp",
      ],
      settings: { foreground: syntax.function },
    },
    {
      name: "Classes, interfaces, types, namespaces and built-ins",
      scope: [
        "support.class",
        "support.type",
        "entity.name.type",
        "entity.name.namespace",
        "entity.other.attribute",
        "entity.name.scope-resolution",
        "entity.name.class",
        "storage.type.numeric.go",
        "storage.type.byte.go",
        "storage.type.boolean.go",
        "storage.type.string.go",
        "storage.type.uintptr.go",
        "storage.type.error.go",
        "storage.type.rune.go",
        "storage.type.cs",
        "storage.type.generic.cs",
        "storage.type.modifier.cs",
        "storage.type.variable.cs",
        "storage.type.annotation.java",
        "storage.type.generic.java",
        "storage.type.java",
        "storage.type.object.array.java",
        "storage.type.primitive.array.java",
        "storage.type.primitive.java",
        "storage.type.token.java",
        "storage.type.groovy",
        "storage.type.annotation.groovy",
        "storage.type.parameters.groovy",
        "storage.type.generic.groovy",
        "storage.type.object.array.groovy",
        "storage.type.primitive.array.groovy",
        "storage.type.primitive.groovy",
        "meta.type.cast.expr",
        "meta.type.new.expr",
        "support.constant.math",
        "support.constant.dom",
        "support.constant.json",
        "entity.other.inherited-class",
        "punctuation.separator.namespace.ruby",
      ],
      settings: { foreground: syntax.type },
    },
    {
      name: "Variables, parameters, properties, attributes and keys",
      scope: [
        "entity.other.attribute-name",
        "meta.structure.dictionary.key.python",
        "support.type.vendored.property-name",
        "support.type.property-name",
        "source.css variable",
        "source.coffee.embedded",
        "support.function.git-rebase",
        "variable",
        "meta.definition.variable.name",
        "support.variable",
        "entity.name.variable",
        "constant.other.placeholder",
        "meta.object-literal.key",
      ],
      settings: { foreground: syntax.variable },
    },
    {
      name: "Constants and enum members",
      scope: ["variable.other.constant", "variable.other.enummember"],
      settings: { foreground: syntax.constant },
    },
    {
      name: "Strings, CSS values and removed lines",
      scope: [
        "string",
        "meta.embedded.assembly",
        "string.tag",
        "string.value",
        "markup.deleted",
        "markup.inline.raw",
        "meta.preprocessor.string",
        "support.constant.property-value",
        "support.constant.font-name",
        "support.constant.media-type",
        "support.constant.media",
        "constant.other.color.rgb-value",
        "constant.other.rgb-value",
        "support.constant.color",
        "punctuation.definition.group.regexp",
        "punctuation.definition.group.assertion.regexp",
        "punctuation.definition.character-class.regexp",
        "punctuation.character.set.begin.regexp",
        "punctuation.character.set.end.regexp",
        "keyword.operator.negation.regexp",
        "support.other.parenthesis.regexp",
      ],
      settings: { foreground: syntax.string },
    },
    {
      name: "Numbers, units and added lines",
      scope: [
        "constant.numeric",
        "keyword.operator.plus.exponent",
        "keyword.operator.minus.exponent",
        "keyword.other.unit",
        "markup.inserted",
        "meta.preprocessor.numeric",
        "constant.sha.git-rebase",
      ],
      settings: { foreground: syntax.number },
    },
    {
      name: "Regular expressions and character classes",
      scope: [
        "string.regexp",
        "constant.regexp",
        "constant.character.character-class.regexp",
        "constant.other.character-class.set.regexp",
        "constant.other.character-class.regexp",
        "constant.character.set.regexp",
      ],
      settings: { foreground: syntax.regexp },
    },
    {
      name: "Escape sequences, CSS selectors and regular expression quantifiers",
      scope: [
        "constant.character.escape",
        "entity.name.tag.css",
        "entity.name.tag.less",
        "entity.other.attribute-name.class.css",
        "source.css entity.other.attribute-name.class",
        "entity.other.attribute-name.id.css",
        "entity.other.attribute-name.parent-selector.css",
        "entity.other.attribute-name.parent.less",
        "source.css entity.other.attribute-name.pseudo-class",
        "entity.other.attribute-name.pseudo-element.css",
        "source.css.less entity.other.attribute-name.id",
        "entity.other.attribute-name.scss",
        "keyword.operator.quantifier.regexp",
      ],
      settings: { foreground: syntax.escape },
    },
    {
      name: "Tag brackets",
      scope: ["punctuation.definition.tag"],
      settings: { foreground: syntax.punctuation },
    },
    {
      name: "Invalid code",
      scope: ["invalid"],
      settings: { foreground: syntax.invalid },
    },
    {
      name: "Markdown bold and headings",
      scope: ["markup.bold", "markup.heading"],
      settings: { foreground: syntax.storage, fontStyle: "bold" },
    },
    {
      name: "Markdown italic",
      scope: ["markup.italic"],
      settings: { foreground: syntax.control, fontStyle: "italic" },
    },
    {
      name: "Emphasis",
      scope: ["emphasis"],
      settings: { fontStyle: "italic" },
    },
    {
      name: "Strong",
      scope: ["strong"],
      settings: { fontStyle: "bold" },
    },
    {
      name: "Underline",
      scope: ["markup.underline"],
      settings: { fontStyle: "underline" },
    },
    {
      name: "Strikethrough",
      scope: ["markup.strikethrough"],
      settings: { fontStyle: "strikethrough" },
    },
  ];
}
