name: PR Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches: [main]

permissions:
  contents: read

jobs:
  commitlint:
    uses: KostaD02/ci/.github/workflows/pr-title.yml@main
